# Basic
title: Cui Tongliang
subtitle: Just do IT later.
welcome_message: 欢迎来到我的个人博客! 
description: 嗨，我是澳客崔郎，一名来自未来的老年人，非著名程序员。
creator: <a href="http://https://cuitongliang.github.io">@cuitongliang</a>

url: "https://cuitongliang.github.io"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: cuitongliang's GitHub,    url: 'https://github.com/cuitongliang'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 Cui Tongliang,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: GcsSloop
    # duoshuo:
# Social
social:
    weibo: GcsSloop
    github: GcsSloop
    twitter: GcsSloop
    rss: /feed.xml
    mail: cuitongliang@foxmail.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-82493667-1
    host: https://cuitongliang.github.io
